version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: aws-training-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,lambda,iam,apigateway,sqs,logs,sts,stepfunctions,dynamodb
      - DEBUG=1
      - ENFORCE_IAM=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOVE_CONTAINERS=true
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - aws-training

networks:
  aws-training:
    driver: bridge
